

[workspace]
members = [
    "chat-lib", 
    "backend", 
    "frontend",
    ]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = {version = "0.4", features = ["serde"]}
